server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: baggage-service

  datasource:
    url: jdbc:postgresql://baggage-system-db-dev.ckzu66q0ovtv.us-east-1.rds.amazonaws.com:5432/baggagedb
    username: postgres
    password: xwGNo1jP{*arymoD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

logging:
  level:
    com.airline.baggage: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always