name: 'Terraform Infrastructure'

on:
  push:
    branches: [ "main" ]
    paths: ['infrastructure/**']
  pull_request:
    branches: [ "main" ]
    paths: ['infrastructure/**']

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/terraform

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Validate Terraform files
    - name: Terraform Validate
      run: terraform validate

    # Check formatting
    - name: Terraform Format Check
      run: terraform fmt -check

    # Generate plan
    - name: Terraform Plan
      run: terraform plan -no-color
      if: github.event_name == 'pull_request'

    # Apply changes (only on main branch push)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
